#!/usr/bin/env bash
# =============================================================================
#  setup_r_sandbox.sh — install R without root, into a relocatable prefix
#
#  Why this exists: some CI/sandbox environments have no root, no conda mirror
#  and no CRAN access, but *can* reach the Ubuntu archive. This script downloads
#  Ubuntu's r-base-core + r-cran-* packages with apt (download-only, all apt
#  state redirected to a writable directory), unpacks them with dpkg-deb, and
#  patches the paths that Debian's R front-end hard-codes.
#
#  On a normal machine you do NOT need this — use envs/environment.yml instead.
#
#  Usage:
#      bash scripts/setup_r_sandbox.sh [PREFIX] [ARCHIVE_DIR]
#      source /tmp/rbin/renv.sh     # then Rscript works
#
#  PREFIX      where to unpack (default /tmp/rroot)
#  ARCHIVE_DIR where .debs are cached (default $PREFIX/../debs); if the .debs
#              are already there the download step is skipped.
# =============================================================================
set -euo pipefail

PREFIX="${1:-/tmp/rroot}"
ARCHIVE_DIR="${2:-}"
EXTRACT="$PREFIX/extracted"
APTROOT="$PREFIX/aptroot"
BINDIR="/tmp/rbin"

PACKAGES=(
  r-base-core
  r-cran-vegan r-cran-mass r-cran-ellipse r-cran-nmf r-cran-nnet r-cran-rpart
  r-cran-randomforest r-cran-gbm r-cran-caret r-cran-rtsne r-cran-uwot
  r-cran-permute r-cran-cluster r-cran-ade4
)

echo "==> prefix: $PREFIX"
mkdir -p "$EXTRACT" "$BINDIR"

# ---------------------------------------------------------------------------
# 1. Acquire .debs (skipped when a populated cache is supplied)
# ---------------------------------------------------------------------------
if [ -n "$ARCHIVE_DIR" ] && compgen -G "$ARCHIVE_DIR/*.deb" > /dev/null; then
  echo "==> using cached .debs in $ARCHIVE_DIR ($(ls "$ARCHIVE_DIR"/*.deb | wc -l) files)"
else
  ARCHIVE_DIR="$APTROOT/var/cache/apt/archives"
  echo "==> downloading .debs into $ARCHIVE_DIR"
  mkdir -p "$APTROOT"/var/lib/dpkg "$APTROOT"/var/cache/apt/archives/partial \
           "$APTROOT"/var/lib/apt/lists/partial "$APTROOT"/etc/apt/apt.conf.d \
           "$APTROOT"/etc/apt/preferences.d
  : > "$APTROOT/var/lib/dpkg/status"
  cp /etc/apt/sources.list "$APTROOT/etc/apt/sources.list"

  APT_OPTS=(-o Dir="$APTROOT"
            -o Dir::State::status="$APTROOT/var/lib/dpkg/status"
            -o APT::Architecture=amd64
            -o Acquire::AllowInsecureRepositories=true
            -o APT::Get::AllowUnauthenticated=true)

  apt-get "${APT_OPTS[@]}" update  >/dev/null 2>&1 || true
  apt-get "${APT_OPTS[@]}" install -y --no-install-recommends -d "${PACKAGES[@]}"
fi

# ---------------------------------------------------------------------------
# 2. Unpack every .deb into the prefix
# ---------------------------------------------------------------------------
echo "==> unpacking $(ls "$ARCHIVE_DIR"/*.deb | wc -l) packages"
for f in "$ARCHIVE_DIR"/*.deb; do
  dpkg-deb -x "$f" "$EXTRACT"
done

R_HOME_NEW="$EXTRACT/usr/lib/R"
[ -x "$R_HOME_NEW/bin/exec/R" ] || { echo "FATAL: R not unpacked"; exit 1; }

# ---------------------------------------------------------------------------
# 3. Patch the paths Debian's front-end hard-codes to /usr/...
#    Without this, R.home("share") resolves to a non-existent directory and
#    every source install dies inside tools:::makeLazyLoading with
#    "missing value where TRUE/FALSE needed".
# ---------------------------------------------------------------------------
echo "==> patching hard-coded paths in bin/R"
sed -i \
  -e "s#^R_HOME_DIR=/usr/lib/R#R_HOME_DIR=$R_HOME_NEW#" \
  -e "s#^R_SHARE_DIR=/usr/share/R/share#R_SHARE_DIR=$EXTRACT/usr/share/R/share#" \
  -e "s#^R_INCLUDE_DIR=/usr/share/R/include#R_INCLUDE_DIR=$EXTRACT/usr/share/R/include#" \
  -e "s#^R_DOC_DIR=/usr/share/R/doc#R_DOC_DIR=$EXTRACT/usr/share/R/doc#" \
  "$R_HOME_NEW/bin/R"

# ---------------------------------------------------------------------------
# 4. Materialise etc/R files that ship as symlinks into /etc/R
# ---------------------------------------------------------------------------
echo "==> materialising etc/R symlinks"
cd "$R_HOME_NEW/etc"
for f in Makeconf Renviron.site Rprofile.site ldpaths repositories; do
  if [ -L "$f" ]; then rm -f "$f"; cp "$EXTRACT/etc/R/$f" "$f"; fi
done
# Renviron itself is generated by the postinst (which never runs here); the
# shipped .orig is the correct template.
if [ -L Renviron ]; then rm -f Renviron; cp Renviron.orig Renviron; fi

# ---------------------------------------------------------------------------
# 5. Rscript shim. The compiled Rscript binary cannot locate R_HOME after
#    relocation, so drive exec/R directly — equivalent for batch use.
# ---------------------------------------------------------------------------
echo "==> writing $BINDIR/Rscript"
cat > "$BINDIR/Rscript" <<WRAP
#!/bin/bash
R_HOME="$R_HOME_NEW"; export R_HOME
export LD_LIBRARY_PATH="\$R_HOME/lib:\${LD_LIBRARY_PATH:-}"
args=("\$@"); file=""; rest=(); exprs=(); i=0
while [ \$i -lt \${#args[@]} ]; do
  a="\${args[\$i]}"
  case "\$a" in
    -e) i=\$((i+1)); exprs+=("\${args[\$i]}") ;;
    --*) ;;
    *) if [ -z "\$file" ] && [ \${#exprs[@]} -eq 0 ]; then file="\$a"; else rest+=("\$a"); fi ;;
  esac
  i=\$((i+1))
done
if [ \${#exprs[@]} -gt 0 ]; then
  printf '%s\n' "\${exprs[@]}" | "\$R_HOME/bin/exec/R" --no-echo --no-restore --args "\${rest[@]}"
else
  "\$R_HOME/bin/exec/R" --no-echo --no-restore --file="\$file" --args "\${rest[@]}"
fi
WRAP
chmod +x "$BINDIR/Rscript"

cat > "$BINDIR/renv.sh" <<ENV
export R_HOME="$R_HOME_NEW"
export LD_LIBRARY_PATH="$R_HOME_NEW/lib:\${LD_LIBRARY_PATH:-}"
export PATH="$BINDIR:$R_HOME_NEW/bin:\$PATH"
export R_LIBS_SITE="$R_HOME_NEW/site-library"
export R_LIBS_USER="$R_HOME_NEW/site-library"
ENV

echo "==> done. Run:  source $BINDIR/renv.sh"
"$BINDIR/Rscript" -e 'cat(R.version.string, "\n")'
